added solution to task 1 "FootballMatch"
mate-academy/jv-football-match pull request #19
Opened 2019-08-19 14:30 UTC by SkaterWeather

2019-08-19 19:15 UTC, boroda4436 commented
Please resolve conflicts

2019-08-20 07:32 UTC, Sofasmile requested changes

2019-08-20 07:32 UTC, Sofasmile commented on src/main/java/core/basesyntax/FootballMatch.java
> +        int dif1 = result1 - result2;
try to simplify
we can implement this method without using redundant variables and method

2019-08-20 13:59 UTC, Sofasmile approved these changes

2019-08-20 13:59 UTC, Sofasmile commented on src/main/java/core/basesyntax/FootballMatch.java
> +}
add a blank line

2019-11-28 12:57 UTC, closed without merging