added solution, probably correct
mate-academy/jv-football-match pull request #26
Opened 2019-08-19 15:12 UTC by gkhrshch

2019-08-20 06:05 UTC, boroda4436 requested changes

2019-08-20 06:05 UTC, boroda4436 commented on src/main/java/core/basesyntax/FootballMatch.java
> +        return playerResult;
it's a bit hard to read

2019-08-20 14:13 UTC, Sofasmile requested changes

2019-08-20 14:13 UTC, Sofasmile commented on src/main/java/core/basesyntax/FootballMatch.java
> +        return (bet1 == result1 && bet2 == result2)
```suggestion
        return (bet1 == result1 && bet2 == result2) ? 2
```

2019-08-20 14:13 UTC, Sofasmile commented on src/main/java/core/basesyntax/FootballMatch.java
> +                      || (bet1 == bet2 && result1 == result2))
```suggestion
                      || (bet1 == bet2 && result1 == result2)) ? 1 : 0;
```

2019-08-21 08:12 UTC, Sofasmile approved these changes

2019-11-28 12:57 UTC, closed without merging